Support hotfix releases

diff --git a/tailor_distro/debian_templates/Dockerfile.j2 b/tailor_distro/debian_templates/Dockerfile.j2
--- a/tailor_distro/debian_templates/Dockerfile.j2
+++ b/tailor_distro/debian_templates/Dockerfile.j2
@@ -93,7 +93,7 @@ RUN echo "AccessKeyId = $AWS_ACCESS_KEY_ID" | tee /etc/apt/s3auth.conf && \
 # TODO(pbovbel) read this from configuration
 RUN curl -fsSL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x142D5F1683E1528B" \
       | gpg --dearmor -o /etc/apt/trusted.gpg.d/tailor.gpg && \
-    echo "deb [arch=amd64] s3://{{ bucket_name }}/{{ release_label }}/ubuntu {{ os_version }}-mirror {{ os_version }}" >> /etc/apt/sources.list && \
+    echo "deb [arch=amd64] s3://{{ bucket_name }}/{{ base_release | default(release_label) }}/ubuntu {{ os_version }}-mirror {{ os_version }}" >> /etc/apt/sources.list && \
     apt-get update && apt-get dist-upgrade -y && \
     apt-get install --no-install-recommends -y \
     python3-colcon-common-extensions && \
@@ -107,11 +107,15 @@ RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2
 RUN echo "Checking whether S3 APT repo is initialized..."; \
     if aws s3api head-object \
         --bucket "{{ bucket_name }}" \
-        --key    "{{ release_label }}/ubuntu/dists/{{ os_version }}/InRelease" \
+        --key    "{{ base_release | default(release_label) }}/ubuntu/dists/{{ os_version }}/InRelease" \
         >/dev/null 2>&1; then \
-      echo "deb [arch=amd64] s3://{{ bucket_name }}/{{ release_label }}/ubuntu {{ os_version }} main" >> /etc/apt/sources.list; \
+    echo "deb [arch=amd64] s3://{{ bucket_name }}/{{ base_release | default(release_label) }}/ubuntu {{ os_version }} main" >> /etc/apt/sources.list; \
     else \
+{% if base_release is defined %}
+            echo "Base release package repo is missing" >&2; exit 1; \
+{% else %}
       echo "Package repo not yet created, continuing"; \
+{% endif %}
     fi
 
 # Install build and run dependencies
